#!/usr/bin/env python3
"""
Main entry point for the vocab scripts
"""

import os.path
import argparse

from kvocab.digest import digest

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog = 'digest',
        description = 'Process subtite file and produce sorted list of morphemes',
    )
    parser.add_argument(
        "language",
        choices = ['ko','yue'],
    )
    parser.add_argument(
        'files',
        nargs=argparse.REMAINDER
    )
    args = parser.parse_args()
    # print(args.language)
    # print(args.files)
    for file in args.files:
        lang_code = {"ko":1,"yue":2}
        print(f"Parsing {file}")
        digest(file, lang_code[args.language])
    
    # if len(sys.argv) > 1:
    #     filename = sys.argv[1]
    #     for file in sys.argv[1:]:
    #         try:
    #             digest(file)
    #         except:
    #             print(f"Couldn't parse file {file}")
    # else:
    #     digest("./data/mlfts14.vtt")
    # # digest("./data/id.xml", language="canto") 