#! /usr/bin/env python3
import argparse
import os

from kvocab.fullprocess import process_file

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog = 'Digest and upload',
        description = 'Digest and upload subtitle file',
    )
    parser.add_argument(
        "language",
        choices = ['ko','yue'],
    )
    parser.add_argument(
        'files',
        nargs=argparse.REMAINDER
    )
    args = parser.parse_args()
    code_dict = {
        "ko" : 1,
        "yue" : 2,
        "ja" : 3
    }
    dir_path = os.path.dirname(os.path.realpath(__file__))
    dbfile = f"{dir_path}/../database.ini"
    lang_code = code_dict[args.language]
    for file in args.files:
        process_file(filename = file, language = lang_code, dbfile=dbfile)
